Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\factures\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\factures\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 3819
"GET /admin/users/user/ HTTP/1.1" 200 12843
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
"GET /admin/users/user/1/change/ HTTP/1.1" 200 24983
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 304 0
"GET /static/admin/js/calendar.js HTTP/1.1" 304 0
"GET /static/admin/css/forms.css HTTP/1.1" 304 0
"GET /static/admin/js/SelectBox.js HTTP/1.1" 304 0
"GET /static/admin/css/widgets.css HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/js/change_form.js HTTP/1.1" 304 0
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
"GET /admin/users/user/1/password/ HTTP/1.1" 200 9331
"GET /static/admin/js/unusable_password_field.js HTTP/1.1" 304 0
"GET /static/admin/css/unusable_password_field.css HTTP/1.1" 304 0
"POST /admin/users/user/1/password/ HTTP/1.1" 302 0
"GET /admin/users/user/1/change/ HTTP/1.1" 200 25119
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"OPTIONS /api/token/ HTTP/1.1" 200 0
"POST /api/token/ HTTP/1.1" 200 489
Watching for file changes with StatReloader
"OPTIONS /api/factures/client/ HTTP/1.1" 200 0
"OPTIONS /api/factures/client/ HTTP/1.1" 200 0
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
"POST /api/token/ HTTP/1.1" 200 489
"OPTIONS /api/users/me/ HTTP/1.1" 200 0
Not Found: /api/users/me/
"GET /api/users/me/ HTTP/1.1" 404 5375
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
"POST /api/token/ HTTP/1.1" 200 489
Not Found: /api/users/me/
"GET /api/users/me/ HTTP/1.1" 404 5375
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
"POST /api/token/ HTTP/1.1" 200 489
Not Found: /api/users/me/
"GET /api/users/me/ HTTP/1.1" 404 5375
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
Unauthorized: /api/token/
"POST /api/token/ HTTP/1.1" 401 63
"POST /api/token/ HTTP/1.1" 200 489
Not Found: /api/users/me/
Not Found: /api/factures/client/
"GET /api/users/me/ HTTP/1.1" 404 5375
"GET /api/factures/client/ HTTP/1.1" 404 5148
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\users\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\users\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\users\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\users\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"OPTIONS /api/token/ HTTP/1.1" 200 0
"POST /api/token/ HTTP/1.1" 200 489
"OPTIONS /api/users/me/ HTTP/1.1" 200 0
"GET /api/users/me/ HTTP/1.1" 200 98
"OPTIONS /api/factures/client/ HTTP/1.1" 200 0
"OPTIONS /api/factures/client/ HTTP/1.1" 200 0
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
"POST /api/token/ HTTP/1.1" 200 489
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
"GET /api/users/me/ HTTP/1.1" 200 96
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 91
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5148
Watching for file changes with StatReloader
"OPTIONS /api/factures/client/ HTTP/1.1" 200 0
"OPTIONS /api/factures/client/ HTTP/1.1" 200 0
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
"OPTIONS /api/token/ HTTP/1.1" 200 0
"POST /api/token/ HTTP/1.1" 200 489
"OPTIONS /api/users/me/ HTTP/1.1" 200 0
"GET /api/users/me/ HTTP/1.1" 200 98
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 96
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 91
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
"OPTIONS /api/factures/me/ HTTP/1.1" 200 0
"OPTIONS /api/factures/me/ HTTP/1.1" 200 0
Unauthorized: /api/factures/me/
"GET /api/factures/me/ HTTP/1.1" 401 172
Unauthorized: /api/factures/me/
"GET /api/factures/me/ HTTP/1.1" 401 172
"OPTIONS /api/documents/me/ HTTP/1.1" 200 0
"OPTIONS /api/documents/me/ HTTP/1.1" 200 0
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/factures/me/
"GET /api/factures/me/ HTTP/1.1" 401 172
Unauthorized: /api/factures/me/
"GET /api/factures/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 91
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 96
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 98
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 91
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
"OPTIONS /api/documents/upload/ HTTP/1.1" 200 0
Unauthorized: /api/documents/upload/
"POST /api/documents/upload/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 91
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 91
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 98
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 91
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Watching for file changes with StatReloader
"OPTIONS /api/factures/client/ HTTP/1.1" 200 0
"OPTIONS /api/factures/client/ HTTP/1.1" 200 0
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
"OPTIONS /api/documents/me/ HTTP/1.1" 200 0
"OPTIONS /api/documents/me/ HTTP/1.1" 200 0
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
"OPTIONS /api/token/ HTTP/1.1" 200 0
"POST /api/token/ HTTP/1.1" 200 489
"OPTIONS /api/users/me/ HTTP/1.1" 200 0
"GET /api/users/me/ HTTP/1.1" 200 98
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 91
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Watching for file changes with StatReloader
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 96
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
"POST /api/token/ HTTP/1.1" 200 489
"GET /api/users/me/ HTTP/1.1" 200 91
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Watching for file changes with StatReloader
"OPTIONS /api/factures/client/ HTTP/1.1" 200 0
"OPTIONS /api/factures/client/ HTTP/1.1" 200 0
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
Not Found: /api/factures/client/
"GET /api/factures/client/ HTTP/1.1" 404 5423
"OPTIONS /api/me/ HTTP/1.1" 200 0
"OPTIONS /api/me/ HTTP/1.1" 200 0
Not Found: /api/me/
"GET /api/me/ HTTP/1.1" 404 3858
Not Found: /api/me/
"GET /api/me/ HTTP/1.1" 404 3858
"OPTIONS /api/factures/me/ HTTP/1.1" 200 0
"OPTIONS /api/factures/me/ HTTP/1.1" 200 0
Unauthorized: /api/factures/me/
"GET /api/factures/me/ HTTP/1.1" 401 172
Unauthorized: /api/factures/me/
"GET /api/factures/me/ HTTP/1.1" 401 172
Unauthorized: /api/factures/me/
"GET /api/factures/me/ HTTP/1.1" 401 172
C:\Users\ahake\Linkompta\backend\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\backend\settings.py changed, reloading.
Watching for file changes with StatReloader
"OPTIONS /api/token/ HTTP/1.1" 200 0
"POST /api/token/ HTTP/1.1" 200 489
"OPTIONS /api/users/me/ HTTP/1.1" 200 0
"GET /api/users/me/ HTTP/1.1" 200 91
"GET /api/factures/me/ HTTP/1.1" 200 2
"GET /api/factures/me/ HTTP/1.1" 200 2
"OPTIONS /api/documents/me/ HTTP/1.1" 200 0
"OPTIONS /api/documents/me/ HTTP/1.1" 200 0
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
Unauthorized: /api/documents/me/
"GET /api/documents/me/ HTTP/1.1" 401 172
"OPTIONS /api/documents/upload/ HTTP/1.1" 200 0
Unauthorized: /api/documents/upload/
"POST /api/documents/upload/ HTTP/1.1" 401 172
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
Bad Request: /api/documents/upload/
"POST /api/documents/upload/ HTTP/1.1" 400 108
Bad Request: /api/documents/upload/
"POST /api/documents/upload/ HTTP/1.1" 400 108
C:\Users\ahake\Linkompta\backend\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\backend\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\backend\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\documents\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\documents\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\documents\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
Bad Request: /api/documents/upload/
"POST /api/documents/upload/ HTTP/1.1" 400 108
"GET /api/documents/me/ HTTP/1.1" 200 2
Bad Request: /api/documents/upload/
"POST /api/documents/upload/ HTTP/1.1" 400 111
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/factures/me/ HTTP/1.1" 200 2
"GET /api/factures/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/factures/me/ HTTP/1.1" 200 2
"GET /api/factures/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
Bad Request: /api/documents/upload/
"POST /api/documents/upload/ HTTP/1.1" 400 111
Bad Request: /api/documents/upload/
"POST /api/documents/upload/ HTTP/1.1" 400 38
Bad Request: /api/documents/upload/
"POST /api/documents/upload/ HTTP/1.1" 400 38
C:\Users\ahake\Linkompta\documents\serializers.py changed, reloading.
Watching for file changes with StatReloader
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
Internal Server Error: /api/documents/upload/
Traceback (most recent call last):
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\documents\views.py", line 42, in perform_create
    client=self.request.user.client_profile,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 534, in __get__
    raise self.RelatedObjectDoesNotExist(
    ...<2 lines>...
    )
users.models.User.client_profile.RelatedObjectDoesNotExist: User has no client_profile.
"POST /api/documents/upload/ HTTP/1.1" 500 111741
C:\Users\ahake\Linkompta\documents\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ahake\Linkompta\documents\permissions.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/documents/upload/
Traceback (most recent call last):
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\documents\views.py", line 48, in perform_create
    serializer.save(
    ~~~~~~~~~~~~~~~^
        client=client_profile,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        file_size=file_obj.size
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1881, in execute_sql
    for sql, params in self.as_sql():
                       ~~~~~~~~~~~^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1806, in as_sql
    self.prepare_value(field, self.pre_save_val(field, obj))
                              ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1750, in pre_save_val
    return field.pre_save(obj, add=True)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 338, in pre_save
    file.save(file.name, file.file, save=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 98, in save
    name = self.field.generate_filename(self.instance, name)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 353, in generate_filename
    filename = self.upload_to(instance, filename)
  File "C:\Users\ahake\Linkompta\documents\models.py", line 6, in document_file_path
    return f'documents/client_{instance.client.id}/{instance.uploaded_at.strftime("%Y-%m")}/{filename}'
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strftime'
"POST /api/documents/upload/ HTTP/1.1" 500 193423
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
Internal Server Error: /api/documents/upload/
Traceback (most recent call last):
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\documents\views.py", line 48, in perform_create
    serializer.save(
    ~~~~~~~~~~~~~~~^
        client=client_profile,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        file_size=file_obj.size
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1881, in execute_sql
    for sql, params in self.as_sql():
                       ~~~~~~~~~~~^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1806, in as_sql
    self.prepare_value(field, self.pre_save_val(field, obj))
                              ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1750, in pre_save_val
    return field.pre_save(obj, add=True)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 338, in pre_save
    file.save(file.name, file.file, save=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 98, in save
    name = self.field.generate_filename(self.instance, name)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 353, in generate_filename
    filename = self.upload_to(instance, filename)
  File "C:\Users\ahake\Linkompta\documents\models.py", line 6, in document_file_path
    return f'documents/client_{instance.client.id}/{instance.uploaded_at.strftime("%Y-%m")}/{filename}'
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strftime'
"POST /api/documents/upload/ HTTP/1.1" 500 193423
"GET /api/factures/me/ HTTP/1.1" 200 2
"GET /api/factures/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
Internal Server Error: /api/documents/upload/
Traceback (most recent call last):
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\documents\views.py", line 48, in perform_create
    serializer.save(
    ~~~~~~~~~~~~~~~^
        client=client_profile,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        file_size=file_obj.size
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1881, in execute_sql
    for sql, params in self.as_sql():
                       ~~~~~~~~~~~^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1806, in as_sql
    self.prepare_value(field, self.pre_save_val(field, obj))
                              ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1750, in pre_save_val
    return field.pre_save(obj, add=True)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 338, in pre_save
    file.save(file.name, file.file, save=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 98, in save
    name = self.field.generate_filename(self.instance, name)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 353, in generate_filename
    filename = self.upload_to(instance, filename)
  File "C:\Users\ahake\Linkompta\documents\models.py", line 6, in document_file_path
    return f'documents/client_{instance.client.id}/{instance.uploaded_at.strftime("%Y-%m")}/{filename}'
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strftime'
"POST /api/documents/upload/ HTTP/1.1" 500 193423
Unauthorized: /api/documents/upload/
"POST /api/documents/upload/ HTTP/1.1" 401 172
C:\Users\ahake\Linkompta\clients\models.py changed, reloading.
Watching for file changes with StatReloader
"POST /api/token/ HTTP/1.1" 200 491
"GET /api/users/me/ HTTP/1.1" 200 105
"GET /api/factures/me/ HTTP/1.1" 200 2
"GET /api/factures/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
Internal Server Error: /api/documents/upload/
Traceback (most recent call last):
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\documents\views.py", line 48, in perform_create
    serializer.save(
    ~~~~~~~~~~~~~~~^
        client=client_profile,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        file_size=file_obj.size
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1881, in execute_sql
    for sql, params in self.as_sql():
                       ~~~~~~~~~~~^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1806, in as_sql
    self.prepare_value(field, self.pre_save_val(field, obj))
                              ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1750, in pre_save_val
    return field.pre_save(obj, add=True)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 338, in pre_save
    file.save(file.name, file.file, save=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 98, in save
    name = self.field.generate_filename(self.instance, name)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 353, in generate_filename
    filename = self.upload_to(instance, filename)
  File "C:\Users\ahake\Linkompta\documents\models.py", line 6, in document_file_path
    return f'documents/client_{instance.client.id}/{instance.uploaded_at.strftime("%Y-%m")}/{filename}'
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strftime'
"POST /api/documents/upload/ HTTP/1.1" 500 193531
"POST /api/token/ HTTP/1.1" 200 491
"GET /api/users/me/ HTTP/1.1" 200 105
"GET /api/documents/me/ HTTP/1.1" 200 2
"GET /api/documents/me/ HTTP/1.1" 200 2
Internal Server Error: /api/documents/upload/
Traceback (most recent call last):
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\documents\views.py", line 48, in perform_create
    serializer.save(
    ~~~~~~~~~~~~~~~^
        client=client_profile,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        file_size=file_obj.size
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\rest_framework\serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1881, in execute_sql
    for sql, params in self.as_sql():
                       ~~~~~~~~~~~^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1806, in as_sql
    self.prepare_value(field, self.pre_save_val(field, obj))
                              ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1750, in pre_save_val
    return field.pre_save(obj, add=True)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 338, in pre_save
    file.save(file.name, file.file, save=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 98, in save
    name = self.field.generate_filename(self.instance, name)
  File "C:\Users\ahake\Linkompta\venv\Lib\site-packages\django\db\models\fields\files.py", line 353, in generate_filename
    filename = self.upload_to(instance, filename)
  File "C:\Users\ahake\Linkompta\documents\models.py", line 6, in document_file_path
    return f'documents/client_{instance.client.id}/{instance.uploaded_at.strftime("%Y-%m")}/{filename}'
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strftime'
"POST /api/documents/upload/ HTTP/1.1" 500 193531
C:\Users\ahake\Linkompta\documents\models.py changed, reloading.
Watching for file changes with StatReloader
